# Generated by Django 4.0 on 2022-07-18 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学生的姓名')),
                ('age', models.SmallIntegerField(default=0, verbose_name='学生年龄')),
            ],
            options={
                'db_table': 'grade_student',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=32, verbose_name='学生的姓名')),
                ('subject_name', models.CharField(max_length=32, verbose_name='科目')),
                ('score', models.FloatField(default=0, verbose_name='分数')),
                ('year', models.SmallIntegerField(verbose_name='年份')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_grade', to='grade.student')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
    ]
